server:
  port: 8002

spring:
  application:
    name: test-model
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.01:3306/yy_edu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#Eureka 配置
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #集群版
      #      defaultZone: http://106.53.108.15:7001/eureka
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
